version: '3.3'

services:
  apiserver:
    image: api-noval-container:1.2
    restart: always
    build: ./api
    ports:
      - "8500:8500"
    depends_on:
      - mongodb
  clientside:
    image: client-noval-container:1.2
    restart: always
    build: ./client
    ports: 
      - "3001:3001"
    depends_on:
      - apiserver
  adminside:
    image: admin-noval-container:1.2
    restart: always
    build: ./admin
    ports:
      - "4000:4000"
    depends_on:
      - apiserver
  mongodb:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - apiDB:/data/db

volumes:
  apiDB: